# .github/workflows/shellcheck.yml
name: ShellCheck Lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: POSIX Shell Analysis
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ShellCheck
        run: |
          shellcheck \
            --shell=sh \
            --exclude=SC1008,SC1091,SC3043,SC2016,SC1090,SC2153,SC2034 \
            usr/lib/matrix/matrix_bot \
            usr/lib/matrix/matrix_send \
            etc/init.d/matrixbot
